Refactor rcfg
WolffunGame/theta-shared-common pull request #54
Opened 2023-03-03 03:08 UTC by trongitnlu

2023-03-06 08:18 UTC, trungdlp-wolffun requested changes

2023-03-06 08:18 UTC, trungdlp-wolffun commented on rcfg/rcfg.go
>  		SetHeader("Accept", "application/json").
Anh làm 1 hàm GetRemoteCfgBaseUrl đi anh, có handle invalid environment luôn, chứ để truyền sai env nó bị lỗi á !

2023-03-07 02:16 UTC, trongitnlu commented on rcfg/rcfg.go
>  		SetHeader("Accept", "application/json").
Anh sửa rồi nha @trungdlp-wolffun

2023-03-15 09:04 UTC, trungdlp-wolffun approved these changes

2023-03-15 09:04 UTC, merged